const phone_numbers = [
  {
    flagCode: "PH",
    country: "Philippines",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 10",
    phoneNumberLengthByCountry_CountryCode: 63,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "US",
    country: "United States",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "JP",
    country: "Japan",
    phoneNumberLengthByCountry_phLengthMax: 13,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 13",
    phoneNumberLengthByCountry_CountryCode: 81,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 10,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CN",
    country: "China",
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 12",
    phoneNumberLengthByCountry_CountryCode: 86,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "ID",
    country: "Indonesia",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 10",
    phoneNumberLengthByCountry_CountryCode: 62,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 1.008,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MY",
    country: "Malaysia",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 9",
    phoneNumberLengthByCountry_CountryCode: 60,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SG",
    country: "Singapore",
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 12",
    phoneNumberLengthByCountry_CountryCode: 65,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 1.008,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TH",
    country: "Thailand",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 or 9",
    phoneNumberLengthByCountry_CountryCode: 66,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 1,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "VN",
    country: "Vietnam",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 10",
    phoneNumberLengthByCountry_CountryCode: 84,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "KR",
    country: "South Korea",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 11",
    phoneNumberLengthByCountry_CountryCode: 82,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 1.002,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 0.082,
  },
  {
    flagCode: "AU",
    country: "Australia",
    phoneNumberLengthByCountry_phLengthMax: 15,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 15",
    phoneNumberLengthByCountry_CountryCode: 61,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GB",
    country: "United Kingdom",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 10",
    phoneNumberLengthByCountry_CountryCode: 44,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CA",
    country: "Canada",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "DE",
    country: "Germany",
    phoneNumberLengthByCountry_phLengthMax: 13,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 13",
    phoneNumberLengthByCountry_CountryCode: 49,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "FR",
    country: "France",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 33,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "ES",
    country: "Spain",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 34,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SA",
    country: "Saudi Arabia",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 966,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "AE",
    country: "United Arab Emirates",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 971,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TW",
    country: "Taiwan",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 886,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 2,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "HK",
    country: "Hong Kong",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4, 8 to 9",
    phoneNumberLengthByCountry_CountryCode: 852,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 1,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "KP",
    country: "North Korea",
    phoneNumberLengthByCountry_phLengthMax: 17,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 17",
    phoneNumberLengthByCountry_CountryCode: 850,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SE",
    country: "Sweden",
    phoneNumberLengthByCountry_phLengthMax: 13,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 13",
    phoneNumberLengthByCountry_CountryCode: 46,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "AT",
    country: "Austria",
    phoneNumberLengthByCountry_phLengthMax: 13,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4 to 13",
    phoneNumberLengthByCountry_CountryCode: 43,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CZ",
    country: "Czechia",
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4 to 12",
    phoneNumberLengthByCountry_CountryCode: 420,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CH",
    country: "Switzerland",
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4 to 12",
    phoneNumberLengthByCountry_CountryCode: 41,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "RS",
    country: "Serbia",
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4 to 12",
    phoneNumberLengthByCountry_CountryCode: 381,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "FI",
    country: "Finland",
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 12",
    phoneNumberLengthByCountry_CountryCode: 358,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "00,99X",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "HR",
    country: "Croatia",
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 12",
    phoneNumberLengthByCountry_CountryCode: 385,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "ME",
    country: "Montenegro",
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4 to 12",
    phoneNumberLengthByCountry_CountryCode: 382,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "PK",
    country: "Pakistan",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 11",
    phoneNumberLengthByCountry_CountryCode: 92,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "IT",
    country: "Italy",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: "",
    phoneNumberLengthByCountry_phLength: "up to 11",
    phoneNumberLengthByCountry_CountryCode: 39,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "PE",
    country: "Peru",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 11",
    phoneNumberLengthByCountry_CountryCode: 51,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "PG",
    country: "Papua New Guinea",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4 to 11",
    phoneNumberLengthByCountry_CountryCode: 675,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "PT",
    country: "Portugal",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: "9 or 11",
    phoneNumberLengthByCountry_CountryCode: 351,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SV",
    country: "El Salvador",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7, 8 or 11",
    phoneNumberLengthByCountry_CountryCode: 503,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "IE",
    country: "Ireland",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 11",
    phoneNumberLengthByCountry_CountryCode: 353,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "UY",
    country: "Uruguay",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4 to 11",
    phoneNumberLengthByCountry_CountryCode: 598,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CY",
    country: "Cyprus",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 or 11",
    phoneNumberLengthByCountry_CountryCode: 357,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "LU",
    country: "Luxembourg",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4 to 11",
    phoneNumberLengthByCountry_CountryCode: 352,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "VA",
    country: "Vatican City",
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: "",
    phoneNumberLengthByCountry_phLength: "up to 11",
    phoneNumberLengthByCountry_CountryCode: 39,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "IN",
    country: "India",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 10",
    phoneNumberLengthByCountry_CountryCode: 91,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "NG",
    country: "Nigeria",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 10",
    phoneNumberLengthByCountry_CountryCode: 234,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 9,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BR",
    country: "Brazil",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
    phoneNumberLengthByCountry_CountryCode: 55,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BD",
    country: "Bangladesh",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 10",
    phoneNumberLengthByCountry_CountryCode: 880,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "RU",
    country: "Russia",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
    phoneNumberLengthByCountry_CountryCode: 7,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 810,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 8,
  },
  {
    flagCode: "MX",
    country: "Mexico",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
    phoneNumberLengthByCountry_CountryCode: 52,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "IR",
    country: "Iran",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 10",
    phoneNumberLengthByCountry_CountryCode: 98,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TR",
    country: "Turkey",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
    phoneNumberLengthByCountry_CountryCode: 90,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "KE",
    country: "Kenya",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 10",
    phoneNumberLengthByCountry_CountryCode: 254,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CO",
    country: "Colombia",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 or 10",
    phoneNumberLengthByCountry_CountryCode: 57,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "009/007/005",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "09/07/05",
  },
  {
    flagCode: "IQ",
    country: "Iraq",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 10",
    phoneNumberLengthByCountry_CountryCode: 964,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "AR",
    country: "Argentina",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
    phoneNumberLengthByCountry_CountryCode: 54,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MG",
    country: "Madagascar",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: "9 to 10",
    phoneNumberLengthByCountry_CountryCode: 261,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "VE",
    country: "Venezuela",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
    phoneNumberLengthByCountry_CountryCode: 58,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SY",
    country: "Syria",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 10",
    phoneNumberLengthByCountry_CountryCode: 963,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "KZ",
    country: "Kazakhstan",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
    phoneNumberLengthByCountry_CountryCode: 7,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 810,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 8,
  },
  {
    flagCode: "ZW",
    country: "Zimbabwe",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 10",
    phoneNumberLengthByCountry_CountryCode: 263,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "DO",
    country: "Dominican Republic",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(809/829) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "GR",
    country: "Greece",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
    phoneNumberLengthByCountry_CountryCode: 30,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BY",
    country: "Belarus",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: "9 to 10",
    phoneNumberLengthByCountry_CountryCode: 375,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 810,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 8,
  },
  {
    flagCode: "LA",
    country: "Laos",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 10",
    phoneNumberLengthByCountry_CountryCode: 856,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "NZ",
    country: "New Zealand",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 3,
    phoneNumberLengthByCountry_phLength: "3 to 10",
    phoneNumberLengthByCountry_CountryCode: 64,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "PR",
    country: "Puerto Rico",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(787/939) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "NA",
    country: "Namibia",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 10",
    phoneNumberLengthByCountry_CountryCode: 264,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "JM",
    country: "Jamaica",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(876) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "TT",
    country: "Trinidad and Tobago",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(868) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "EE",
    country: "Estonia",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 10",
    phoneNumberLengthByCountry_CountryCode: 372,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BS",
    country: "Bahamas",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(242) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "BB",
    country: "Barbados",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(246) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "LC",
    country: "Saint Lucia",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(758) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "GU",
    country: "Guam",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(671) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "GD",
    country: "Grenada",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(473) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "VC",
    country: "Saint Vincent and the Grenadines",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(784) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "AG",
    country: "Antigua and Barbuda",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(268) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "VI",
    country: "United States Virgin Islands",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(340) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "KY",
    country: "Cayman Islands",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(345) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "DM",
    country: "Dominica",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(767) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "BM",
    country: "Bermuda",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(441) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "TC",
    country: "Turks and Caicos Islands",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(649) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "KN",
    country: "Saint Kitts and Nevis",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(869) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "AS",
    country: "American Samoa",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(684) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "SX",
    country: "Sint Maarten",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(721) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "VG",
    country: "British Virgin Islands",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(284) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "SM",
    country: "San Marino",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 10",
    phoneNumberLengthByCountry_CountryCode: 378,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "AI",
    country: "Anguilla",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(264) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "MS",
    country: "Montserrat",
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: "(664) + 7",
    phoneNumberLengthByCountry_CountryCode: 1,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "ET",
    country: "Ethiopia",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 251,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "EG",
    country: "Egypt",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 9",
    phoneNumberLengthByCountry_CountryCode: 20,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CD",
    country: "DR Congo",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 9",
    phoneNumberLengthByCountry_CountryCode: 243,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TZ",
    country: "Tanzania",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 255,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "ZA",
    country: "South Africa",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 27,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MM",
    country: "Myanmar",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 9",
    phoneNumberLengthByCountry_CountryCode: 95,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SD",
    country: "Sudan",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 249,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "UG",
    country: "Uganda",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 256,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "DZ",
    country: "Algeria",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 or 9",
    phoneNumberLengthByCountry_CountryCode: 213,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "AF",
    country: "Afghanistan",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 93,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "YE",
    country: "Yemen",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 9",
    phoneNumberLengthByCountry_CountryCode: 967,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "AO",
    country: "Angola",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 244,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "UA",
    country: "Ukraine",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 380,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MA",
    country: "Morocco",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 212,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "PL",
    country: "Poland",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 9",
    phoneNumberLengthByCountry_CountryCode: 48,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "UZ",
    country: "Uzbekistan",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 998,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 810,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 8,
  },
  {
    flagCode: "MZ",
    country: "Mozambique",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 258,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GH",
    country: "Ghana",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 9",
    phoneNumberLengthByCountry_CountryCode: 233,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "NP",
    country: "Nepal",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 977,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "LK",
    country: "Sri Lanka",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 94,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "ZM",
    country: "Zambia",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 260,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CL",
    country: "Chile",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 56,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "1YZ0",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "1YZ",
  },
  {
    flagCode: "SN",
    country: "Senegal",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 221,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "RO",
    country: "Romania",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 40,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "NL",
    country: "Netherlands",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 31,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "RW",
    country: "Rwanda",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 250,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BE",
    country: "Belgium",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 32,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "JO",
    country: "Jordan",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 9",
    phoneNumberLengthByCountry_CountryCode: 962,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TJ",
    country: "Tajikistan",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 992,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 810,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 8,
  },
  {
    flagCode: "AZ",
    country: "Azerbaijan",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 994,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "IL",
    country: "Israel",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 972,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "12,013,014",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "HU",
    country: "Hungary",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 36,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: 6,
  },
  {
    flagCode: "LY",
    country: "Libya",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: "8 to 9",
    phoneNumberLengthByCountry_CountryCode: 218,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "KG",
    country: "Kyrgyzstan",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 996,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "PY",
    country: "Paraguay",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 9",
    phoneNumberLengthByCountry_CountryCode: 595,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BG",
    country: "Bulgaria",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 9",
    phoneNumberLengthByCountry_CountryCode: 359,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SK",
    country: "Slovakia",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4 to 9",
    phoneNumberLengthByCountry_CountryCode: 421,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GE",
    country: "Georgia",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 995,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "AL",
    country: "Albania",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 3,
    phoneNumberLengthByCountry_phLength: "3 to 9",
    phoneNumberLengthByCountry_CountryCode: 355,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GQ",
    country: "Equatorial Guinea",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 240,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "IS",
    country: "Iceland",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 or 9",
    phoneNumberLengthByCountry_CountryCode: 354,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GP",
    country: "Guadeloupe",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 590,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MQ",
    country: "Martinique",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 596,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GF",
    country: "French Guiana",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
    phoneNumberLengthByCountry_CountryCode: 594,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "AD",
    country: "Andorra",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6, 8 or 9",
    phoneNumberLengthByCountry_CountryCode: 376,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "LI",
    country: "Liechtenstein",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 9",
    phoneNumberLengthByCountry_CountryCode: 423,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MC",
    country: "Monaco",
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 9",
    phoneNumberLengthByCountry_CountryCode: 377,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CI",
    country: "Ivory Coast",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 225,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CM",
    country: "Cameroon",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 237,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "NE",
    country: "Niger",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 227,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "ML",
    country: "Mali",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 223,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BF",
    country: "Burkina Faso",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 226,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MW",
    country: "Malawi",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 or 8",
    phoneNumberLengthByCountry_CountryCode: 265,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TD",
    country: "Chad",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 235,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SO",
    country: "Somalia",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 to 8",
    phoneNumberLengthByCountry_CountryCode: 252,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GT",
    country: "Guatemala",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 502,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "EC",
    country: "Ecuador",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 593,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "KH",
    country: "Cambodia",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 855,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "001, 007",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GN",
    country: "Guinea",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 224,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BJ",
    country: "Benin",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 229,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BI",
    country: "Burundi",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 257,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BO",
    country: "Bolivia",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 591,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TN",
    country: "Tunisia",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 216,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "HT",
    country: "Haiti",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 509,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "HN",
    country: "Honduras",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 504,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CU",
    country: "Cuba",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 8",
    phoneNumberLengthByCountry_CountryCode: 53,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 119,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TG",
    country: "Togo",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 228,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SL",
    country: "Sierra Leone",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 232,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TM",
    country: "Turkmenistan",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 993,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 810,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 8,
  },
  {
    flagCode: "NI",
    country: "Nicaragua",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 505,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "DK",
    country: "Denmark",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 45,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "LB",
    country: "Lebanon",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 8",
    phoneNumberLengthByCountry_CountryCode: 961,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "LR",
    country: "Liberia",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 8",
    phoneNumberLengthByCountry_CountryCode: 231,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CF",
    country: "Central African Republic",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 236,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "OM",
    country: "Oman",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 8",
    phoneNumberLengthByCountry_CountryCode: 968,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "NO",
    country: "Norway",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 or 8",
    phoneNumberLengthByCountry_CountryCode: 47,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CR",
    country: "Costa Rica",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 506,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "KW",
    country: "Kuwait",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 or 8",
    phoneNumberLengthByCountry_CountryCode: 965,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "PA",
    country: "Panama",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 or 8",
    phoneNumberLengthByCountry_CountryCode: 507,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MN",
    country: "Mongolia",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 8",
    phoneNumberLengthByCountry_CountryCode: 976,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 1,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "QA",
    country: "Qatar",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 3,
    phoneNumberLengthByCountry_phLength: "3 to 8",
    phoneNumberLengthByCountry_CountryCode: 974,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BA",
    country: "Bosnia and Herzegovina",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 387,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MD",
    country: "Moldova",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 373,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "AM",
    country: "Armenia",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 374,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "LT",
    country: "Lithuania",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 370,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BW",
    country: "Botswana",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 8",
    phoneNumberLengthByCountry_CountryCode: 267,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "LS",
    country: "Lesotho",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 266,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SI",
    country: "Slovenia",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 386,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "LV",
    country: "Latvia",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 or 8",
    phoneNumberLengthByCountry_CountryCode: 371,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BH",
    country: "Bahrain",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 973,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SZ",
    country: "Eswatini",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 8",
    phoneNumberLengthByCountry_CountryCode: 268,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BT",
    country: "Bhutan",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 8",
    phoneNumberLengthByCountry_CountryCode: 975,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MO",
    country: "Macau",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 8",
    phoneNumberLengthByCountry_CountryCode: 853,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MT",
    country: "Malta",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 356,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CW",
    country: "Curacao",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: "7 to 8",
    phoneNumberLengthByCountry_CountryCode: 599,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GI",
    country: "Gibraltar",
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
    phoneNumberLengthByCountry_CountryCode: 350,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MR",
    country: "Mauritania",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 222,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "ER",
    country: "Eritrea",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 291,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GM",
    country: "Gambia",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 220,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GA",
    country: "Gabon",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 or 7",
    phoneNumberLengthByCountry_CountryCode: 241,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MU",
    country: "Mauritius",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 230,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "FJ",
    country: "Fiji",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 679,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "KM",
    country: "Comoros",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 269,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GY",
    country: "Guyana",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 592,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 1,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SR",
    country: "Suriname",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: "6 to 7",
    phoneNumberLengthByCountry_CountryCode: 597,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MV",
    country: "Maldives",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 960,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CV",
    country: "Cape Verde",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 238,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BN",
    country: "Brunei",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 673,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "BZ",
    country: "Belize",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 501,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "VU",
    country: "Vanuatu",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 or 7",
    phoneNumberLengthByCountry_CountryCode: 678,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "ST",
    country: "Sao Tome and Principe",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 239,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "WS",
    country: "Samoa",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 3,
    phoneNumberLengthByCountry_phLength: "3 to 7",
    phoneNumberLengthByCountry_CountryCode: 685,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SC",
    country: "Seychelles",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 248,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "FM",
    country: "Micronesia",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 691,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "AW",
    country: "Aruba",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 297,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TO",
    country: "Tonga",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 or 7",
    phoneNumberLengthByCountry_CountryCode: 676,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "MH",
    country: "Marshall Islands",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 692,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: 1,
  },
  {
    flagCode: "PW",
    country: "Palau",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
    phoneNumberLengthByCountry_CountryCode: 680,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: 11,
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "NR",
    country: "Nauru",
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: "4 or 7",
    phoneNumberLengthByCountry_CountryCode: 674,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "DJ",
    country: "Djibouti",
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
    phoneNumberLengthByCountry_CountryCode: 253,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "NC",
    country: "New Caledonia",
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
    phoneNumberLengthByCountry_CountryCode: 687,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "PF",
    country: "French Polynesia",
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
    phoneNumberLengthByCountry_CountryCode: 689,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "FO",
    country: "Faroe Islands",
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
    phoneNumberLengthByCountry_CountryCode: 298,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "GL",
    country: "Greenland",
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
    phoneNumberLengthByCountry_CountryCode: 299,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "WF",
    country: "Wallis and Futuna",
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
    phoneNumberLengthByCountry_CountryCode: 681,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TV",
    country: "Tuvalu",
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: "5 or 6",
    phoneNumberLengthByCountry_CountryCode: 688,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "PM",
    country: "Saint Pierre and Miquelon",
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
    phoneNumberLengthByCountry_CountryCode: 508,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "SB",
    country: "Solomon Islands",
    phoneNumberLengthByCountry_phLengthMax: 5,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: 5,
    phoneNumberLengthByCountry_CountryCode: 677,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "KI",
    country: "Kiribati",
    phoneNumberLengthByCountry_phLengthMax: 5,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: 5,
    phoneNumberLengthByCountry_CountryCode: 686,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "CK",
    country: "Cook Islands",
    phoneNumberLengthByCountry_phLengthMax: 5,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: 5,
    phoneNumberLengthByCountry_CountryCode: 682,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "FK",
    country: "Falkland Islands",
    phoneNumberLengthByCountry_phLengthMax: 5,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: 5,
    phoneNumberLengthByCountry_CountryCode: 500,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "TK",
    country: "Tokelau",
    phoneNumberLengthByCountry_phLengthMax: 4,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: 4,
    phoneNumberLengthByCountry_CountryCode: 690,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
  {
    flagCode: "NU",
    country: "Niue",
    phoneNumberLengthByCountry_phLengthMax: 4,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: 4,
    phoneNumberLengthByCountry_CountryCode: 683,
    phoneNumberLengthByCountry_phLength_InternationalPrefix: "",
    phoneNumberLengthByCountry_phLength_NationalPrefix: "",
  },
];
