name: Run Jest Tests

on:
  pull_request:
    branches:
      - Development
      - Testing
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Frontend dependencies
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      # Backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      # Run Jest tests (backend)
      - name: Run Jest
        run: npm test
        working-directory: backend
